env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  '@typescript-eslint/no-use-before-define':
    - error
  comma-dangle: 0
  implicit-arrow-linebreak: 0
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/prefer-default-export: 0
  jsx-a11y/anchor-is-valid: off
  max-len: 0
  no-use-before-define: 0
  no-confusing-arrow: 0
  object-curly-newline: 0
  prettier/prettier: error
  react/jsx-filename-extension:
    - error
    - extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  react/jsx-one-expression-per-line: off
  react/jsx-props-no-spreading: off
  react/prop-types: off
  react/react-in-jsx-scope: off
settings:
  react:
    version: detect
  import/resolver:
    node:
      extensions:
        - .ts
        - .tsx
    typescript: {}
